"""train_model.py
-----------------
Script to train and save the KNN sport recommender model.
This script handles the training pipeline: load data from database, 
train the model, and save it to disk for production use.
"""

from ml.recommender import KNNSportRecommender
from utils.db import get_ml_training_data_cli

def train_and_save_model():
    """Train the KNN recommender and save it for production use"""
    print("\n" + "="*60)
    print("KNN SPORT RECOMMENDER - MODEL TRAINING")
    print("="*60 + "\n")
    
    # Load training data from database via client layer
    print("Loading training data from database...")
    training_data = get_ml_training_data_cli()
    
    # Create and train recommender
    recommender = KNNSportRecommender(n_neighbors=10)  # Create a new recommender that finds 10 similar sports
    recommender.load_and_train(training_data)  # Train model with loaded data
    
    # Save the model (prepare for production deployment)
    print("\n" + "="*60)  # Print visual separator to distinguish model saving section
    from pathlib import Path
    recommender.save_model(str(Path("ml/models/knn_recommender.joblib")))  # Persist complete trained model bundle to disk for instant loading in production Streamlit app
    print("✅ KNN ML Model ready for production!")  # Confirm successful model training and saving ready for integration with web application
    print("="*60 + "\n")  # Print closing visual separator for clean console output

if __name__ == "__main__":
    train_and_save_model()

# Parts of this codebase were developed with the assistance of AI-based tools (Cursor and Github Copilot)
# All outputs generated by such systems were reviewed, validated, and modified by the author.